### ISSUE TITLE
Internal Dashboard - Watcher : Requirement Definition

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/Design_-_Contents#20]
## Description

Define requirement for Internal Dashboard on Project Selling & Farming overview

**Comment by G2CARBZ** [comment]
- Update Youtube URL with the Channel Youtube Link instead 
- Banner Image URL => what's the purpose? if useless then remove
- Project metadata: small symbole to showcase which ones are dynamic (status; end year; total carbon units; projected carbon units; audited carbon units) or static
- - Audited shouldn't be 0 
- Contracts information : put addresses at the end of the tab 
- Project tab: 
- - Symbol: BANFARCARB
- - token supply : issue right now
- - Certifier account??? 
- - Garder uniquement : symbol, token supply, total value, project value 
- Minter
- - Max value per tx: 0.000001 ??? 
- - Garder uniquement : unit price, remaining value, reserved value, max value, payment token 
- Yielder
- - Define total 
- - Define max
- - APR to remove 
- Offseter
- - Total et max definition 
- Price Curve
- - Prix d'achat line 
- - Prix de vente
- - Prix Forecast (McKinsey / Bloomberg) - https://prod-carbonable-calculator.fly.dev/simulator
- Remove cumulative sale curve
- APR
- - Actual + forecast * quantity (DB from https://prod-carbonable-calculator.fly.dev/simulator)
- - whereas now it's only actuals 
- Link to Bloomberg, Mckinsey etc.

**Comment by schwepps** [comment]
I'm ok with most of it.
But I'm strongly against putting data that are not on-chain.

**Comment by schwepps** [comment]
@G2CARBZ :
- Contracts information : put addresses at the end of the tab => What does it mean. There are only addresses in this tab.
- Token supply => I don't think it's an issue. We might have 55 tokens worth much more value.
- Small symbol to showcase which ones are dynamic => We don't have this information on-chain. We would need to maintain it manually. I don't think we should do that. In case you still want to do it, what's the symbol?
- For everything we want to hide, we should just have a private/public visibility switch in .env because everything is useful to check smart contracts deployment.
- I don't understand what needs to be done with the APR curve. What quantity are we talking about?

@cloudvenger @tekkac 
- What is the certifier account?
- What should be the value of Max value per tx?
- What is the difference between total and max value?
- Do we have the price of a ton of carbon when we buy the project onchain?

@Khyati729 we will need to split this ticket.
1 ticket in the watcher repo and 1 ticket for carbon protocol.

The carbon protocol ticker should include all the data update:
- youtube link
- audited CC
- symbol
- etc.

The watcher ticket should include everything that imply dev on the frontend.
Also, in the header we will remove Carbonable and rename to RWA and we will need to add an extra level to select carbonable first. The idea behind that would be to be able later to showcase other RWA in the tool.

**Comment by cloudvenger** [comment]
as Schepps, I'm strongly against putting data that are not on-chain. 
The purpose of the Watcher is to be simple and direct connected to the blockchain, without Indexer. 

- Token supply => Agreed, the important element is the Value. In addition to that, as we don't have the Smart Contract ERC-721 Enumerable extension, we can not have this information.
- To confirm with Trunk, but for small symbol to showcase which ones are dynamic, maybe we can have the information from component/contract which generate Metadata
- we should just have a private/public visibility switch in .env  => I am aligne with this solution +1 

Answering to direct questions 

- What should be the value of Max value per tx? => We dont have any technical restriction, it's more a product feature/question. If no restriction, this means that someone can easily, in one transaction, buy everything and then sell it on secondary market. But to counter the max per tx, you can multi-call and use bot to call Smart Contract, so it's not a strong restriction. 

- What is the difference between total and max value? => The difference is total value is the amount currently minted and max value is the maximum value which can be minted. 

- Do we have the price of a ton of carbon when we buy the project onchain? => we have a variable, which is call "ton_equivalent" which indicate how much cost a gram of carbon for 1 10e-6 $ (what is the ratio between a gram of carbon and 1 of 10e-6 $)

**Comment by G2CARBZ** [comment]
@schwepps 
- Contracts information : put addresses at the end of the tab => instead of adresses being the first column, put it as the last one (i.e; start by project and end by adresses)
- Token supply => We don't understand the definition of token supply then. Needs to be specified. As it stands for me is "how many tokens are there in this collection", and if that's the case, it's not 55. Same issue for las delicias. 
- Small symbol to showcase which ones are dynamic => Symbol: * and we put a legend somewhere with * = dynamic data 
- For everything we want to hide, we should just have a private/public visibility switch in .env because everything is useful to check smart contracts deployment. => agreed 
- I don't understand what needs to be done with the APR curve. What quantity are we talking about? => It was not clear my bad. My point is to replicate what we had in the calculator/simulator. Actuals with a solid line, and forecasts with dotted lines. And forecasts being linked to the forecasted price at each period of time.

**Comment by cloudvenger** [comment]
To have the "price per ton of carbon" when funding the project, you need to call and do the following operation :
_price ton carbon = ((get_project_value * get_ton_equivalent) / get_final_absorption) / 1000000_
